version: "3"
services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hthrone-server
      - POSTGRES_PASSWORD=hthrone-pass
      - POSTGRES_DB=hthrone
  game:
    build: .
    environment:
      - HTHRONE_DB_URI=postgres://hthrone-server:hthrone-pass@postgres/hthrone?sslmode=disable
      - HTHRONE_ENDPOINT=/hthrone
      - HTHRONE_DOMAIN=twitter.summerofgame.com
      - HTHRONE_TWITTER_ENV_NAME=hthrone
      #- HTHRONE_DEBUG=1
    env_file:
      - .env
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - certs:/app/certs
    depends_on:
      - postgres
volumes:
  dbdata:
  certs: